name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Frontend
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Backend
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Backend Check
        run: |
          cd backend
          echo "Backend OK"